---
- name: Install Jenkins
  hosts: 172.18.20.92
  become: yes
  vars:
    jenkins_version: "{{ jenkins_version }}"  # Set the desired Jenkins version, e.g., "2.387"
    desired_state: present  # Set to 'present' to install Jenkins or 'absent' to remove it

  tasks:
    - name: Import Jenkins public key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
        state: present

    - name: Install Jenkins on CentOS
      when: ansible_distribution == 'CentOS'
      yum:
        name: "jenkins-{{ jenkins_version }}"
        state: "{{ desired_state }}"

    - name: Open Firewall Port 8080
      ansible.builtin.firewalld:
        port: 8080/tcp
        permanent: true
        state: "{{ 'enabled' if desired_state == 'present' else 'disabled' }}"
      when: ansible_distribution in ['CentOS', 'Ubuntu']
    
    - name: Start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started
      when: desired_state == 'present'
